version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: github-nippou-darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
  - id: github-nippou-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./main.go
  - id: github-nippou-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./main.go

archives:
  - formats: [ "zip" ]
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - CHANGELOG.md
      - LICENSE.txt
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: github-nippou
    repository:
      owner: masutaka
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
    homepage: "https://github.com/masutaka/github-nippou"
    description: "Print today's your GitHub activity for issues and pull requests"
    license: "MIT"
    install: |
      bin.install 'github-nippou'

      # Install bash completion
      output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'bash')
      (bash_completion/'github-nippou').write output

      # Install fish completion
      output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'fish')
      (fish_completion/'github-nippou.fish').write output

      # Install zsh completion
      output = Utils.safe_popen_read("#{bin}/github-nippou", 'completion', 'zsh')
      (zsh_completion/'_github-nippou').write output
    test: |
      system 'github-nippou', 'version'
