name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    uses: masutaka/actions/.github/workflows/actionlint.yml@main
    permissions:
      contents: read
  codeql:
    permissions:
      actions: read
      checks: read
      contents: read
      security-events: write
    uses: masutaka/actions/.github/workflows/codeql.yml@main
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: make test-all
  pushover:
    name: pushover if failure
    if: github.ref_name == github.event.repository.default_branch && failure()
    needs: [actionlint, codeql, test]
    uses: masutaka/actions/.github/workflows/pushover.yml@main
    permissions:
      contents: read
    secrets:
      PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
